### ISSUE TITLE
Feedback: 19/02 Playtest

### ISSUE THREAD

**Issue by xezno** [apetavern/sbox-fortwars#29]
- [x] Inventory slots are often randomly ordered on player spawn
- [x] Reload weapon automatically when it's empty and you try to fire
- [x] Remove blocks from disconnected players
  - [x] ~~Only do this if a timer reaches a certain threshold; if not, re-assign all those blocks to newly joined client instance~~
- [x] Remove team balancing or balance it in a way that players get all their blocks back when balanced
- [x] Adjust & balance sniper scope, needs to be easier to use
- [x] Give maps a `fw_config` entity that allows them to configure block limits, player limits, spawn timers, etc.
- [x] Make Team-specific force fields actually work and stop bullets/players
- [x] Only let people change class when they're in the spawn room
- [ ] #30
- [x] Option to delete blocks you've placed
- [ ] Investigate dedicated server performance after several level changes
- [ ] Add 2fort to map pool

**Comment by ShadowBrian** [comment]
https://github.com/apetavern/sbox-fortwars/commit/7b55b43c368254a36a17019220f218d3ddb962d2
That was my fix for the inventory slots problem, but the root cause is OnChildAdded being ran in a random order when multiple children are added in one frame.
A "proper" fix would be to add some UI data to the weapons or something so the UI can show them in the same order regardless of which slot they're in, or get Entity.OnChildAdded working better which is gonna be a Facepunch thing
